# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: nullpixel's Blog
email: blog@nullpixel.uk
description: >
  Hi there. I'm nullpixel, an iOS & Web developer. I make some pretty cool stuff,
  learn about it here!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.nullpixel.uk"
lang: en-GB
timezone: UTC

twitter_username: nullriver
github_username:  nullpixel
comments: false

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

theme: jekyll-apple
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - jekyll-apple.gemspec
  - screenshot.png
  - vendor
