title: nullpixel's Blog
email: blog@nullpixel.uk
description: >
  Hi there. I'm nullpixel, an iOS & Web developer. I make some pretty cool stuff,
  learn about it here!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.nullpixel.uk"
lang: en-GB
timezone: UTC

twitter_username: nullriver
github_username:  nullpixel
comments: false

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

theme: jekyll-apple

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - jekyll-apple.gemspec
  - screenshot.png
  - vendor
